# Generated by Django 2.2.6 on 2021-09-22 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmwebapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.IntegerField(choices=[(0, 'Not defined'), (1, 'Action'), (2, 'Thriller'), (3, 'Science Fiction'), (4, 'Fantasy'), (5, 'Comedy'), (6, 'Romantic'), (7, 'Western'), (8, 'Crime'), (9, 'Drama')], default=-1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
