# Generated by Django 3.1 on 2021-10-11 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmwebapp', '0002_auto_20210922_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.IntegerField(choices=[(1, 'Not defined'), (2, 'Action'), (3, 'Thriller'), (4, 'Science Fiction'), (5, 'Fantasy'), (6, 'Comedy'), (7, 'Romantic'), (8, 'Western'), (9, 'Crime'), (10, 'Drama')], default=-1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
